PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE condemned (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, time DATETIME NOT NULL);
INSERT INTO condemned VALUES(4,'Condemned One','2024-05-19 16:38:59');
COMMIT;
